[package]
name = "datawrangler"
version = "0.1.0"
edition = "2021"
authors = ["Peter Simonsson <peter.simonsson@gmail.com>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
crossterm = "0.27.0"
datafusion = "33.0.0"
nom = "7.1.3"
rustyline = "13.0.0"
thiserror = "1.0.52"
tokio = { version = "1.35.0", features = ["rt-multi-thread", "macros"] }
